export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESETPWD_SUCCESS = "RESETPWD_SUCCESS";
export const RESETPWD_FAIL = "RESETPWD_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//Conversations
export const SET_CONVERSATION = "SET_CONVERSATION";
export const SET_CONVERSATION_MESSAGES = "SET_CONVERSATION_MESSAGES";
